export const SEARCH_ORGANIZATIONS = "SEARCH_ORGANIZATIONS";
export const GET_ORGANIZATION = "GET_ORGANIZATION";
export const CLEAR_ORGANIZATIONS = "CLEAR_ORGANIZATIONS";
export const GET_REPOS = "GET_REPOS";
export const SET_LOADING = "SET_LOADING";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
